FROM python:3.6

RUN echo "nameserver 8.8.8.8" >> /etc/resolv.conf
RUN echo "nameserver 8.8.4.4" >> /etc/resolv.conf

# set the working directory in the container
WORKDIR /code

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip install --default-timeout=1000 -r requirements.txt

# copy the content of the local files to the working directory
COPY config.py .
COPY kafka_topic_creator.py .
COPY persister.py .
COPY master.py .

CMD [ "python", "./master.py" ]