version: '2'

services:
  kafka-cluster:
    container_name: kafka-cluster
    image: landoop/fast-data-dev:2.5.1
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
      SAMPLEDATA: 0
#    volumes:
#    - ./connector:/kafka-config
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker

  neo4j:
    image: neo4j:4.0.3
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/batikan
      NEO4J_dbms_logs_debug_level: DEBUG
