FROM python:3.6

# set the working directory in the container
WORKDIR /code

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# copy the content of the local files to the working directory
COPY worker.py .
COPY config.py .

CMD [ "python", "./worker.py" ]